sudo: false
language: generic


cache:
  directories:
    - $HOME/.stack


# Test on multiple operating systems
os:
  - osx
  - linux
  - windows


# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev


# Download and unpack the stack executable
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'


# Build dependencies
install:
  - stack --no-terminal --install-ghc test --only-dependencies


# Build the package, its tests, and its docs and run the tests
script:
  - stack --no-terminal test --haddock --no-haddock-deps
